# Generated by Django 6.1 on 2026-09-21 11:09

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', validators=[blog.validators.validate_image_size, blog.validators.validate_image_extension]),
        ),
    ]
